version: '2'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.0
    container_name: keycloak
    ports:
      - 5000:8080
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=admin
      - DB_PASSWORD=admin
      # uncomment for initial user creation
      # - KEYCLOAK_USER=admin
      # - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
    command: 
      - -Dkeycloak.profile.feature.upload_scripts=enabled
      - -Dkeycloak.profile.feature.token_exchange=enabled
      - -Dkeycloak.profile=preview
      # uncomment for user import/export
        #- -Dkeycloak.migration.action=export
        #- -Dkeycloak.migration.provider=singleFile 
        #- -Dkeycloak.migration.file=/tmp/users/export.json

    restart: unless-stopped
    volumes:
      - keycloak-themes:/opt/jboss/keycloak/themes
      - keycloak-deployments:/opt/jboss/keycloak/standalone/deployments
      # to export/import users
      # - keycloak-users:/tmp/users
    networks:
      - backbone-network
    
  redis:
    image: library/redis:6.0.8-alpine
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - backbone-network

  postgres:
    image: library/postgres:13-alpine
    container_name: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - backbone-network
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    restart: unless-stopped
    networks:
      - backbone-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - mysql:/docker-entrypoint-initdb.d
    networks:
      - backbone-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80
    volumes:
      - phpmyadmin:/var/www/html
    networks:
      - backbone-network

volumes:
  keycloak-themes:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/data/keycloak/themes'
  keycloak-deployments:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/data/keycloak/deployments'
  # keycloak-users:
  #   driver: local
  #   driver_opts:
  #     type: 'none'
  #     o: 'bind'
  #     device: '${PWD}/data/keycloak/users'
  redis:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/data/redis'
  postgres:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/data/postgres'
  pgadmin:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/data/pgadmin'
  mysql:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/data/mysql'
  phpmyadmin:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/data/phpmyadmin'

networks:
  backbone-network:
    driver: bridge
